
(function(){
var app=document.getElementById('app');
var modal=document.getElementById('tem-modal');
var KEY='safety_data_v2';
var TOUCH_DY=8;
var touch=[];
var state={route:'hub',flightId:'',legId:'',paxMode:'FULL'};

var VIP1_FIELDS=['Peligros del campo','Posiciones de parqueo','Entradas / salidas recomendadas','Posibles amenazas'];
var MISSION=[
{id:'m1',s:'BRIEFING DE LA MISION',l:'Lider de mision - NOMBRADO',r:1},
{id:'m2',s:'BRIEFING DE LA MISION',l:'Reconocimiento del campo/sitio - REALIZADO',r:0},
{id:'m3',s:'BRIEFING DE LA MISION',l:'Meteorologia - CHEQUEADA',r:1},
{id:'m4',s:'BRIEFING DE LA MISION',l:'Alternos - VERIFICADOS',r:1},
{id:'m5',s:'BRIEFING DE LA MISION',l:'Vuelo en formacion - ESTABLECER',r:0},
{id:'m6',s:'BRIEFING DE LA MISION',l:'Tarjeta de riesgo - DILIGENCIADA',r:1},
{id:'m7',s:'BRIEFING DE LA MISION',l:'Controlador aereo - VERIFICADO',r:0},
{id:'m8',s:'BRIEFING DE LA MISION',l:'Frecuencias - ESTABLECIDAS',r:1},
{id:'m9',s:'BRIEFING DE LA MISION',l:'Mapa de riesgos - VERIFICADO',r:0},
{id:'m10',s:'BRIEFING DE LA MISION',l:'Riesgo BASH - VERIFICADO',r:0},
{id:'m11',s:'BRIEFING DE LA MISION',l:'Equipo de mision - REQUERIDO',r:0}
];
var CREW=[
{id:'c1',s:'INTRODUCCION / ROLES',l:'Roles PF/PM/Tecnico/TTV confirmados',r:1},
{id:'c2',s:'INTRODUCCION / ROLES',l:'Autonomia / control psicofisico / ETTO',r:1},
{id:'c3',s:'INTRODUCCION / ROLES',l:'Resistencia de tripulacion (descanso)',r:1},
{id:'c4',s:'RIESGO / ORDEN',l:'Tarjeta de riesgo',r:1},
{id:'c5',s:'RIESGO / ORDEN',l:'Orden de vuelo',r:1},
{id:'c6',s:'MISION / SAFE START',l:'Mision (Seguridad - Cumplimiento - Servicio)',r:1},
{id:'c7',s:'MISION / SAFE START',l:'Safe Start (prisa / frustracion / fatiga / complacencia)',r:1},
{id:'c8',s:'TEM',l:'Amenazas identificadas y gestionadas',r:1},
{id:'c9',s:'TEM',l:'Errores identificados y solucionados',r:1},
{id:'c10',s:'TEM',l:'UAS recuperados',r:1},
{id:'c11',s:'TEM',l:'Regla: cualquiera anuncia amenaza/error y aplica FACDEE',r:1},
{id:'c12',s:'AIRMANSHIP',l:'Disciplina',r:1},
{id:'c13',s:'AIRMANSHIP',l:'Habilidades y destreza',r:1},
{id:'c14',s:'AIRMANSHIP',l:'Conocimiento y conciencia situacional',r:1},
{id:'c15',s:'AIRMANSHIP',l:'Juicio',r:1},
{id:'c16',s:'EJECUCION / PLAN',l:'Rutas / altitudes / MEA',r:1},
{id:'c17',s:'EJECUCION / PLAN',l:'Tiempo estimado en ruta',r:0},
{id:'c18',s:'EJECUCION / PLAN',l:'Combustible y reabastecimiento',r:1},
{id:'c19',s:'EJECUCION / PLAN',l:'Pasajeros, abordaje y desabordaje',r:1},
{id:'c20',s:'EJECUCION / PLAN',l:'Meteo / engelamiento / ASHTAM',r:1},
{id:'c21',s:'AERONAVE / EMERGENCIAS',l:'Equipo de emergencia',r:1},
{id:'c22',s:'AERONAVE / EMERGENCIAS',l:'Procedimientos de emergencia y salida',r:1},
{id:'c23',s:'AERONAVE / EMERGENCIAS',l:'Acciones PF/PM y responsabilidades tecnico/pax',r:1},
{id:'c24',s:'REGLAS',l:'Golden Rules (Volar / Navegar / Comunicar)',r:1},
{id:'c25',s:'REGLAS',l:'Regla de dos retos',r:1},
{id:'c26',s:'REGLAS',l:'FACDEE',r:1}
];
var PAX_FULL=[
{name:'Presentacion',items:['Presentacion de la tripulacion']},
{name:'Datos de vuelo',items:['Rutas','Altitud','Tiempo en ruta','Condiciones meteorologicas']},
{name:'Procedimientos normales',items:['Entrada y salida del helicoptero','Asientos','Cinturones de seguridad','Movimientos dentro del helicoptero','Comunicaciones internas','Seguridad del equipo','No fumar','Oxigeno y mascara','Reabastecimiento de combustible','Proteccion de oidos','Salida de la aeronave','Equipo de supervivencia']},
{name:'Procedimientos de emergencia',items:['Salidas de emergencia','Equipo de emergencia (crash kit, chalecos, extintor)','Aterrizaje de emergencia','Amarizaje forzoso']}
];
var PAX_QUICK=['No tocar controles / seguir instrucciones','Cinturon y ajuste','Headset / intercom basico','Seguridad cerca del rotor / aproximacion','Salidas de emergencia + evacuacion','Brace / postura ante emergencia','Equipo basico (chaleco/extintor si aplica)'];
var DEBRIEF=[
{id:'d1',l:'Seguridad/UAS: se deterioraron margenes de seguridad?',r:1},
{id:'d2',l:'Amenazas y errores: te preparamos? lo reparamos?',r:1},
{id:'d3',l:'Normas: violamos SOP? Si es asi, por que?',r:1},
{id:'d4',l:'Preguntas sin respuesta / problemas no resueltos',r:0},
{id:'d5',l:'Oportunidades de mejora para el proximo vuelo',r:1}
];
function uid(){return 'id_'+Date.now()+'_'+Math.floor(Math.random()*1e6);} 
function now(){return new Date().toISOString();}
function today(){return new Date().toISOString().slice(0,10);} 
function esc(v){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function m(el,s){if(!el)return false;var f=el.matches||el.msMatchesSelector||el.webkitMatchesSelector;return f?f.call(el,s):false;}
function c(el,s){while(el&&el!==document){if(m(el,s))return el;el=el.parentNode;}return null;}
function q(root,s){return root.querySelector(s);} 
function load(){try{var r=localStorage.getItem(KEY);var d=r?JSON.parse(r):{};if(!d.flights)d.flights=[];if(!d.briefings)d.briefings={};if(!d.debriefs)d.debriefs={};if(!d.temLogs)d.temLogs=[];return d;}catch(e){return {flights:[],briefings:{},debriefs:{},temLogs:[]};}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d));}
function parse(){var x=(location.hash||'').replace(/^#\/?/,'');if(!x)return {route:'hub',flightId:'',legId:''};var p=x.split('/');return {route:p[0]||'hub',flightId:p[1]||'',legId:p[2]||''};}
function setHash(route,flightId,legId){var h='#/'+(route||'hub');if(flightId)h+='/'+flightId;if(legId)h+='/'+legId;if(location.hash===h){render();return;}location.hash=h;}
function mkFlight(){return {id:uid(),dateISO:today(),operator:'HELO OPS',aircraftType:'AW139',tailNumber:'',missionType:'NORMAL',base:'',legs:[{id:uid(),from:'',to:'',etdISO:'',etaISO:''}],crew:[{id:uid(),role:'PIC',name:''},{id:uid(),role:'PF',name:''},{id:uid(),role:'PM',name:''},{id:uid(),role:'TECH',name:''},{id:uid(),role:'TTV',name:''}],paxCount:0,createdAt:now(),updatedAt:now()};}
function defFlight(d){if(d.flights.length)return d.flights[0];var f=mkFlight();d.flights.push(f);save(d);return f;}
function getFlight(d,id){for(var i=0;i<d.flights.length;i++)if(d.flights[i].id===id)return d.flights[i];return null;}
function getLeg(f,id){if(!f||!f.legs||!f.legs.length)return null;for(var i=0;i<f.legs.length;i++)if(f.legs[i].id===id)return f.legs[i];return f.legs[0];}
function kB(f,l,t){return [f||'',l||'',t||''].join('|');}
function kD(f,l){return [f||'',l||''].join('|');}
function clone(list){var o=[];for(var i=0;i<list.length;i++)o.push({id:list[i].id,section:list[i].s,label:list[i].l,required:!!list[i].r,checked:false,details:{}});return o;}
function getB(d,f,l,t){var k=kB(f.id,l.id,t);if(!d.briefings[k]){d.briefings[k]={id:uid(),flightId:f.id,legId:l.id,type:t,status:'NOT_STARTED',startedAt:now(),completedAt:'',notes:'',items:[],paxChecks:{},paxMode:'FULL',acks:[]};if(t==='MISSION')d.briefings[k].items=clone(MISSION);if(t==='CREW')d.briefings[k].items=clone(CREW);}return d.briefings[k];}
function getD(d,f,l){var k=kD(f.id,l.id);if(!d.debriefs[k])d.debriefs[k]={id:uid(),flightId:f.id,legId:l.id,fields:{d1:'',d2:'',d3:'',d4:'',d5:''},actions:[]};return d.debriefs[k];}
function ensureAcks(b,f){var roles=[];if(b.type==='MISSION')roles=['PIC'];if(b.type==='CREW')roles=['PF','PM','PIC'];if(b.type==='PAX')roles=['TTV','PIC'];for(var i=0;i<roles.length;i++){var r=roles[i],e=null,n='';for(var a=0;a<b.acks.length;a++)if(b.acks[a].role===r)e=b.acks[a];for(var c=0;c<f.crew.length;c++)if(f.crew[c].role===r)n=f.crew[c].name||'';if(!e)b.acks.push({role:r,name:n,acknowledged:false,acknowledgedAt:''});else if(!e.name&&n)e.name=n;}}
function hasAck(b){for(var i=0;i<b.acks.length;i++){var a=b.acks[i];if(!a.acknowledged)continue;if(b.type==='MISSION'&&a.role==='PIC')return true;if(b.type==='CREW'&&(a.role==='PF'||a.role==='PM'||a.role==='PIC'))return true;if(b.type==='PAX'&&(a.role==='TTV'||a.role==='PIC'))return true;}return b.type==='DEBRIEF';}
function applyVIP1(f,b){if(b.type!=='MISSION')return;var it=null;for(var i=0;i<b.items.length;i++)if(b.items[i].id==='m2')it=b.items[i];if(!it)return;if(f.missionType==='VIP1'){it.required=true;for(var d=0;d<VIP1_FIELDS.length;d++)if(typeof it.details[VIP1_FIELDS[d]]!=='string')it.details[VIP1_FIELDS[d]]='';}}
function cntReq(b){var t=0,c=0;for(var i=0;i<b.items.length;i++)if(b.items[i].required){t++;if(b.items[i].checked)c++;}return {t:t,c:c};}
function cntPax(b,m){var t=0,c=0;if(m==='QUICK')t=PAX_QUICK.length;else for(var s=0;s<PAX_FULL.length;s++)t+=PAX_FULL[s].items.length;var p=m==='QUICK'?'Q:':'F:';for(var k in b.paxChecks)if(b.paxChecks.hasOwnProperty(k)&&k.indexOf(p)===0&&b.paxChecks[k])c++;return {t:t,c:c};}
function cntDeb(d){var t=0,c=0;for(var i=0;i<DEBRIEF.length;i++)if(DEBRIEF[i].r){t++;if(String(d.fields[DEBRIEF[i].id]||'').trim())c++;}return {t:t,c:c};}
function canDone(f,b,d){if(b.type==='MISSION'||b.type==='CREW'){for(var i=0;i<b.items.length;i++)if(b.items[i].required&&!b.items[i].checked)return {ok:false,r:'Falta item requerido: '+b.items[i].label};if(b.type==='MISSION'&&f.missionType==='VIP1'){var m2=null;for(i=0;i<b.items.length;i++)if(b.items[i].id==='m2')m2=b.items[i];if(!m2||!m2.checked)return {ok:false,r:'VIP1 requiere Reconocimiento del campo/sitio.'};for(var z=0;z<VIP1_FIELDS.length;z++)if(!String((m2.details||{})[VIP1_FIELDS[z]]||'').trim())return {ok:false,r:'VIP1 requiere: '+VIP1_FIELDS[z]};}if(!hasAck(b))return {ok:false,r:'Falta ACK por rol.'};return {ok:true};}
if(b.type==='PAX'){var p=cntPax(b,b.paxMode||'FULL');if(p.c<p.t)return {ok:false,r:'Completa items del modo '+(b.paxMode||'FULL')};if(!hasAck(b))return {ok:false,r:'Falta ACK TTV o PIC.'};return {ok:true};}
if(b.type==='DEBRIEF'){var x=cntDeb(d);if(x.c<x.t)return {ok:false,r:'Faltan campos obligatorios de Debrief.'};return {ok:true};}
return {ok:false,r:'Tipo no soportado'};}
function pill(s){if(s==='DONE')return '<span class="pill done">DONE</span>';if(s==='IN_PROGRESS')return '<span class="pill progress">IN PROGRESS</span>';if(s==='NEEDS_REVIEW')return '<span class="pill review">NEEDS REVIEW</span>';return '<span class="pill">NOT STARTED</span>';}
function attrs(o){var x='';for(var k in o)if(o.hasOwnProperty(k))x+=' '+k+'="'+esc(o[k])+'"';return x;}
function row(kind,a,checked,label,meta){var id='chk_'+kind+'_'+Math.floor(Math.random()*1e8);return '<div class="check-item" role="checkbox" tabindex="0" aria-checked="'+(checked?'true':'false')+'" data-kind="'+esc(kind)+'"'+attrs(a)+'><input class="check-input" type="checkbox" id="'+id+'" '+(checked?'checked':'')+' /><label class="check-item-main" for="'+id+'"><span class="check-toggle" aria-hidden="true"></span><span class="check-label">'+esc(label)+'</span><span class="check-meta">'+esc(meta||'')+'</span></label></div>';}
function group(items){var map={},out=[];for(var i=0;i<items.length;i++){var s=items[i].section||'--';if(!map[s]){map[s]={n:s,it:[]};out.push(map[s]);}map[s].it.push(items[i]);}return out;}
function notify(sec,sub,c,t){var p=t?Math.round((c/t)*100):0;if(window.parent&&window.parent!==window){window.parent.postMessage({type:'SAFETY_POSITION',section:String(sec||'').toUpperCase(),subsection:String(sub||'').toUpperCase(),checked:c||0,total:t||0,percent:p},'*');}}
function modeSet(m){document.body.classList.remove('theme-day','theme-night','theme-nvg');if(m==='day')document.body.classList.add('theme-day');else if(m==='nvg')document.body.classList.add('theme-nvg');else document.body.classList.add('theme-night');}
function modeInit(){modeSet('night');window.addEventListener('message',function(e){var d=e&&e.data?e.data:null;if(!d||d.type!=='AW139_MODE')return;modeSet(d.mode);});}
function ackSection(b,f){ensureAcks(b,f);var h='<section class="card" style="box-shadow:none; margin-top:10px;"><div class="card-head"><div><h3 class="card-title" style="font-size:20px;">ACK POR ROL</h3><p class="card-sub">Minimo 1 ACK valido segun criterio operacional.</p></div></div><div class="card-body">';for(var i=0;i<b.acks.length;i++){var a=b.acks[i],txt=a.role+' - Leido y entendido'+(a.acknowledgedAt?' ('+a.acknowledgedAt+')':'');h+='<div class="check-list">'+row('ack-item',{'data-ack-index':String(i)},!!a.acknowledged,txt,'ACK')+'</div><label class="field" style="margin-top:8px;"><span>Nombre '+esc(a.role)+'</span><input type="text" data-ack-name-index="'+i+'" value="'+esc(a.name||'')+'" /></label>';}return h+'</div></section>';}
function hub(d,f,l){var mB=getB(d,f,l,'MISSION'),cB=getB(d,f,l,'CREW'),pB=getB(d,f,l,'PAX'),dB=getB(d,f,l,'DEBRIEF');ensureAcks(mB,f);ensureAcks(cB,f);ensureAcks(pB,f);var done=(mB.status==='DONE'?1:0)+(cB.status==='DONE'?1:0)+(pB.status==='DONE'?1:0)+(dB.status==='DONE'?1:0);var pct=Math.round(done/4*100);
var fo='',lo='',crew='';for(var i=0;i<d.flights.length;i++)fo+='<option value="'+esc(d.flights[i].id)+'" '+(d.flights[i].id===f.id?'selected':'')+'>Vuelo '+esc(d.flights[i].dateISO)+' - '+esc(d.flights[i].missionType||'NORMAL')+'</option>';for(i=0;i<f.legs.length;i++)lo+='<option value="'+esc(f.legs[i].id)+'" '+(f.legs[i].id===l.id?'selected':'')+'>'+esc((f.legs[i].from||'--')+' -> '+(f.legs[i].to||'--'))+'</option>';for(i=0;i<f.crew.length;i++)crew+='<label class="field"><span>'+esc(f.crew[i].role)+'</span><input type="text" data-crew-index="'+i+'" value="'+esc(f.crew[i].name||'')+'" /></label>';
var mt=['NORMAL','VIP1','NVG','OVERWATER','FORMATION','OTHER'],opts='';for(i=0;i<mt.length;i++)opts+='<option value="'+mt[i]+'" '+(f.missionType===mt[i]?'selected':'')+'>'+mt[i]+'</option>';
var h='';h+='<section class="card"><div class="card-head"><div><h2 class="card-title">Safety Hub</h2><p class="card-sub">Briefings de Mision, Tripulacion, Pasajeros y Debrief con TEM + Airmanship.</p></div><div class="header-actions"><button class="btn" data-action="new-flight">+ Nuevo Vuelo</button></div></div><div class="card-body">';
h+='<div class="row"><label class="field"><span>Vuelo</span><select data-action="select-flight">'+fo+'</select></label><label class="field"><span>Leg</span><select data-action="select-leg">'+lo+'</select></label><div style="display:flex; align-items:flex-end;"><button class="btn" data-action="add-leg">+ Leg</button></div></div>';
h+='<div class="row" style="margin-top:10px;"><label class="field"><span>Fecha</span><input type="date" data-flight-field="dateISO" value="'+esc(f.dateISO||'')+'" /></label><label class="field"><span>Matricula</span><input type="text" data-flight-field="tailNumber" value="'+esc(f.tailNumber||'')+'" /></label><label class="field"><span>Tipo de mision</span><select data-flight-field="missionType">'+opts+'</select></label><label class="field"><span>PAX</span><input type="number" min="0" data-flight-field="paxCount" value="'+esc(f.paxCount||0)+'" /></label><label class="field"><span>Origen</span><input type="text" data-leg-field="from" value="'+esc(l.from||'')+'" /></label><label class="field"><span>Destino</span><input type="text" data-leg-field="to" value="'+esc(l.to||'')+'" /></label></div>';
h+='<div style="margin-top:10px;" class="progress"><span style="width:'+pct+'%"></span></div><div class="hint" style="margin-top:6px;">Progreso modulo: '+done+'/4 bloques DONE.</div>';
h+='<div class="grid-cards" style="margin-top:10px;"><div class="module-card"><h3>Mision</h3><p>Riesgo, meteo, alternos, VIP1.</p>'+pill(mB.status)+'<div class="actions" style="justify-content:flex-start;"><button class="btn primary" data-action="go" data-route="mission">Abrir</button></div></div><div class="module-card"><h3>Tripulacion</h3><p>CRM/TEM + Airmanship + FACDEE.</p>'+pill(cB.status)+'<div class="actions" style="justify-content:flex-start;"><button class="btn primary" data-action="go" data-route="crew">Abrir</button></div></div><div class="module-card"><h3>Pasajeros</h3><p>Modo FULL o QUICK (&lt;=90s).</p>'+pill(pB.status)+'<div class="actions" style="justify-content:flex-start;"><button class="btn primary" data-action="go" data-route="pax">Abrir</button></div></div><div class="module-card"><h3>Debrief</h3><p>Post-fase / post-vuelo + acciones.</p>'+pill(dB.status)+'<div class="actions" style="justify-content:flex-start;"><button class="btn primary" data-action="go" data-route="debrief">Abrir</button></div></div></div>';
h+='<section class="card" style="box-shadow:none; margin-top:10px;"><div class="card-head"><div><h3 class="card-title" style="font-size:20px;">Tripulacion</h3><p class="card-sub">Datos para ACK por rol.</p></div></div><div class="card-body"><div class="row">'+crew+'</div></div></section>';
h+='<section class="card" style="box-shadow:none; margin-top:10px;"><div class="card-head"><div><h3 class="card-title" style="font-size:20px;">TEM y Airmanship</h3><p class="card-sub">Referencias visuales integradas al modulo Safety & Briefings.</p></div></div><div class="card-body"><div class="visual-grid"><figure class="visual-item"><img src="./assets/facdee_01.jpeg" alt="Debriefing TEM" /><figcaption>Debriefing operativo: Seguridad/UAS, Amenazas/Errores, SOP, Pendientes, Mejora.</figcaption></figure><figure class="visual-item"><img src="./assets/facdee_02.jpeg" alt="Airmanship" /><figcaption>Airmanship: disciplina, habilidades, destreza, conocimiento, conciencia situacional y juicio.</figcaption></figure><figure class="visual-item visual-item-logo"><img src="./assets/aguila_uno_logo.png" alt="Aguila 1" /><figcaption>Identidad operacional del modulo Safety.</figcaption></figure><figure class="visual-item visual-item-logo"><img src="./assets/fac_logo.png" alt="FAC" /><figcaption>Referencia institucional para briefing y debrief.</figcaption></figure></div></div></section>';
h+='</div></section>';app.innerHTML=h;notify('SAFETY BRIEFINGS','HUB',done,4);} 
function missionCrew(d,f,l,type){var b=getB(d,f,l,type);ensureAcks(b,f);if(type==='MISSION')applyVIP1(f,b);var sec=group(b.items),body='';for(var s=0;s<sec.length;s++){body+='<details class="accordion" open><summary><button type="button" class="accordion-summary"><span>'+esc(sec[s].n)+'</span><span class="pill">'+esc(type)+'</span></button></summary><div class="accordion-body"><div class="check-list">';for(var i=0;i<sec[s].it.length;i++){var it=sec[s].it[i];body+=row('briefing-item',{'data-item-id':it.id},!!it.checked,it.label,it.required?'REQ':'OPT');if(type==='MISSION'&&f.missionType==='VIP1'&&it.id==='m2'){body+='<div class="row">';for(var z=0;z<VIP1_FIELDS.length;z++){var cv=(it.details&&it.details[VIP1_FIELDS[z]])||'';body+='<label class="field"><span>'+esc(VIP1_FIELDS[z])+' (obligatorio VIP1)</span><input type="text" data-vip-item-id="m2" data-vip-key="'+esc(VIP1_FIELDS[z])+'" value="'+esc(cv)+'" /></label>';}body+='</div>';}}
body+='</div></div></details>';}
var cnt=cntReq(b),h='<section class="card"><div class="card-head"><div><h2 class="card-title">'+(type==='MISSION'?'Briefing Mision':'Briefing Tripulacion')+'</h2><p class="card-sub">Vuelo '+esc(f.dateISO)+' | Leg '+esc((l.from||'--')+' -> '+(l.to||'--'))+'</p></div><div class="header-actions"><button class="btn" data-action="go" data-route="hub">Hub</button></div></div><div class="card-body">';
if(type==='CREW'){h+='<section class="card" style="box-shadow:none; margin-bottom:10px;"><div class="card-head"><div><h3 class="card-title" style="font-size:20px;">Guia TEM + Airmanship</h3><p class="card-sub">Aplicacion directa para CRM/TEM, FACDEE y juicio operacional.</p></div></div><div class="card-body"><div class="quick-chips"><button type="button" class="chip">THREAT</button><button type="button" class="chip">ERROR</button><button type="button" class="chip">UAS</button><button type="button" class="chip">PREPARAR</button><button type="button" class="chip">REPARAR</button><button type="button" class="chip">RECUPERAR</button></div><div class="visual-grid"><figure class="visual-item"><img src="./assets/facdee_01.jpeg" alt="TEM Skills" /><figcaption>TEM: anunciar amenaza/error, cross-check y recuperar estado de aeronave.</figcaption></figure><figure class="visual-item"><img src="./assets/facdee_02.jpeg" alt="Airmanship pilares" /><figcaption>Airmanship: disciplina + habilidades + conocimiento + conciencia + juicio.</figcaption></figure></div></div></section>';}
h+=body+'<label class="field" style="margin-top:10px;"><span>Notas operacionales</span><textarea data-briefing-notes="1">'+esc(b.notes||'')+'</textarea></label>'+ackSection(b,f)+'<div class="actions"><button class="btn" data-action="save-briefing">Guardar</button><button class="btn primary" data-action="done-briefing">Cerrar (DONE)</button></div><div class="hint" style="margin-top:8px;">Progreso requerido: '+cnt.c+'/'+cnt.t+'</div></div></section>';app.innerHTML=h;notify('SAFETY BRIEFINGS',type==='MISSION'?'BRIEFING MISION':'BRIEFING TRIPULACION',cnt.c,cnt.t);} 
function pax(d,f,l){var b=getB(d,f,l,'PAX');ensureAcks(b,f);if(b.paxMode!=='FULL'&&b.paxMode!=='QUICK')b.paxMode='FULL';if(state.paxMode!==b.paxMode)state.paxMode=b.paxMode;var tabs='<div class="tabs"><button class="tab '+(state.paxMode==='FULL'?'active':'')+'" data-action="pax-mode" data-mode="FULL">FULL</button><button class="tab '+(state.paxMode==='QUICK'?'active':'')+'" data-action="pax-mode" data-mode="QUICK">QUICK</button></div>';
var list='';if(state.paxMode==='QUICK'){list+='<section class="card" style="box-shadow:none;"><div class="card-body"><div class="check-list">';for(var qx=0;qx<PAX_QUICK.length;qx++){var qk='Q:'+qx;list+=row('pax-item',{'data-key':qk},!!b.paxChecks[qk],PAX_QUICK[qx],'QUICK');}list+='</div><div class="actions" style="justify-content:flex-start;"><button class="btn" data-action="show-emergency-card">Ver Tarjeta de Emergencia</button></div></div></section>';}else{for(var s=0;s<PAX_FULL.length;s++){list+='<details class="accordion" open><summary><button type="button" class="accordion-summary"><span>'+esc(PAX_FULL[s].name)+'</span><span class="pill">FULL</span></button></summary><div class="accordion-body"><div class="check-list">';for(var p=0;p<PAX_FULL[s].items.length;p++){var fk='F:'+s+':'+p;list+=row('pax-item',{'data-key':fk},!!b.paxChecks[fk],PAX_FULL[s].items[p],'PAX');}list+='</div></div></details>';}}
var cp=cntPax(b,state.paxMode);var h='<section class="card"><div class="card-head"><div><h2 class="card-title">Briefing Pasajeros</h2><p class="card-sub">Vuelo '+esc(f.dateISO)+' | Leg '+esc((l.from||'--')+' -> '+(l.to||'--'))+'</p></div><div class="header-actions"><button class="btn" data-action="go" data-route="hub">Hub</button></div></div><div class="card-body">'+tabs+'<div style="margin-top:10px;">'+list+'</div>'+ackSection(b,f)+'<div class="actions"><button class="btn" data-action="save-briefing">Guardar</button><button class="btn primary" data-action="done-briefing">Cerrar (DONE)</button></div><div class="hint" style="margin-top:8px;">Modo '+esc(state.paxMode)+': '+cp.c+'/'+cp.t+' items.</div></div></section>';app.innerHTML=h;notify('SAFETY BRIEFINGS','BRIEFING PAX '+state.paxMode,cp.c,cp.t);} 
function debrief(d,f,l){var b=getB(d,f,l,'DEBRIEF'),x=getD(d,f,l),fh='',ah='';for(var i=0;i<DEBRIEF.length;i++)fh+='<label class="field"><span>'+esc(DEBRIEF[i].l)+(DEBRIEF[i].r?' (obligatorio)':'')+'</span><textarea data-debrief-field="'+DEBRIEF[i].id+'">'+esc(x.fields[DEBRIEF[i].id]||'')+'</textarea></label>';
if(!x.actions.length)ah='<div class="hint">Sin acciones registradas.</div>';else for(i=0;i<x.actions.length;i++){var a=x.actions[i];ah+='<section class="card" style="box-shadow:none;"><div class="card-body"><div class="row"><label class="field"><span>Titulo</span><input type="text" data-action-edit-idx="'+i+'" data-action-edit-key="title" value="'+esc(a.title||'')+'" /></label><label class="field"><span>Owner</span><input type="text" data-action-edit-idx="'+i+'" data-action-edit-key="owner" value="'+esc(a.owner||'')+'" /></label><label class="field"><span>Due Date</span><input type="date" data-action-edit-idx="'+i+'" data-action-edit-key="dueDateISO" value="'+esc(a.dueDateISO||'')+'" /></label><label class="field"><span>Severidad</span><select data-action-edit-idx="'+i+'" data-action-edit-key="severity"><option value="LOW" '+(a.severity==='LOW'?'selected':'')+'>LOW</option><option value="MED" '+(a.severity==='MED'?'selected':'')+'>MED</option><option value="HIGH" '+(a.severity==='HIGH'?'selected':'')+'>HIGH</option></select></label><label class="field"><span>Status</span><select data-action-edit-idx="'+i+'" data-action-edit-key="status"><option value="OPEN" '+(a.status==='OPEN'?'selected':'')+'>OPEN</option><option value="IN_PROGRESS" '+(a.status==='IN_PROGRESS'?'selected':'')+'>IN_PROGRESS</option><option value="DONE" '+(a.status==='DONE'?'selected':'')+'>DONE</option></select></label><div style="display:flex;align-items:flex-end;"><button class="btn danger" data-action="action-del" data-idx="'+i+'">Eliminar</button></div></div></div></section>';}
var cd=cntDeb(x);b.status=cd.c===cd.t?'DONE':'IN_PROGRESS';if(b.status==='DONE')b.completedAt=now();save(d);
var h='<section class="card"><div class="card-head"><div><h2 class="card-title">Debrief</h2><p class="card-sub">Vuelo '+esc(f.dateISO)+' | Leg '+esc((l.from||'--')+' -> '+(l.to||'--'))+'</p></div><div class="header-actions"><button class="btn" data-action="go" data-route="hub">Hub</button></div></div><div class="card-body">'+fh+'<section class="card" style="box-shadow:none; margin-top:10px;"><div class="card-head"><div><h3 class="card-title" style="font-size:20px;">Acciones Correctivas</h3><p class="card-sub">owner + dueDate + severity + status.</p></div><div class="header-actions"><button class="btn" data-action="action-add">+ Accion</button></div></div><div class="card-body">'+ah+'</div></section><div class="actions"><button class="btn" data-action="save-debrief">Guardar</button><button class="btn primary" data-action="done-debrief">Cerrar (DONE)</button></div><div class="hint" style="margin-top:8px;">Campos obligatorios: '+cd.c+'/'+cd.t+'</div></div></section>';app.innerHTML=h;notify('SAFETY BRIEFINGS','DEBRIEF',cd.c,cd.t);} 
function render(){var d=load(),p=parse(),f=defFlight(d);state.route=p.route||'hub';state.flightId=p.flightId||state.flightId||f.id;f=getFlight(d,state.flightId)||f;state.flightId=f.id;var l=getLeg(f,p.legId||state.legId);if(!l){l={id:uid(),from:'',to:'',etdISO:'',etaISO:''};f.legs.push(l);save(d);}state.legId=l.id;if(state.route==='mission')return missionCrew(d,f,l,'MISSION');if(state.route==='crew')return missionCrew(d,f,l,'CREW');if(state.route==='pax')return pax(d,f,l);if(state.route==='debrief')return debrief(d,f,l);state.route='hub';return hub(d,f,l);} 
function temSave(){var d=load();d.temLogs.push({id:uid(),flightId:state.flightId,legId:state.legId,phase:(document.getElementById('tem_phase').value||'').trim(),severity:(document.getElementById('tem_severity').value||'').trim(),threat:(document.getElementById('tem_threat').value||'').trim(),error:(document.getElementById('tem_error').value||'').trim(),uas:(document.getElementById('tem_uas').value||'').trim(),recoveryAction:(document.getElementById('tem_recovery').value||'').trim(),facdee:{factor:(document.getElementById('f_factor').value||'').trim(),alternatives:(document.getElementById('f_alt').value||'').trim(),consequences:(document.getElementById('f_cons').value||'').trim(),decision:(document.getElementById('f_dec').value||'').trim(),execution:(document.getElementById('f_exec').value||'').trim(),evaluation:(document.getElementById('f_eval').value||'').trim()},createdAt:now()});save(d);document.getElementById('tem_threat').value='';document.getElementById('tem_error').value='';document.getElementById('tem_uas').value='';document.getElementById('tem_recovery').value='';document.getElementById('f_factor').value='';document.getElementById('f_alt').value='';document.getElementById('f_cons').value='';document.getElementById('f_dec').value='';document.getElementById('f_exec').value='';document.getElementById('f_eval').value='';modal.classList.remove('show');modal.setAttribute('aria-hidden','true');alert('Log TEM guardado.');}
function fac(f){if(!f)return '';var p=[];if(f.factor)p.push('F:'+f.factor);if(f.alternatives)p.push('A:'+f.alternatives);if(f.consequences)p.push('C:'+f.consequences);if(f.decision)p.push('D:'+f.decision);if(f.execution)p.push('E:'+f.execution);if(f.evaluation)p.push('Ev:'+f.evaluation);return p.join(' | ');} 
function exportR(){var d=load(),f=getFlight(d,state.flightId);if(!f)return;var l=getLeg(f,state.legId);if(!l)return;var m=getB(d,f,l,'MISSION'),cB=getB(d,f,l,'CREW'),pB=getB(d,f,l,'PAX'),x=getD(d,f,l);if(f.missionType==='VIP1'){applyVIP1(f,m);var vr=canDone(f,m,x);if(!vr.ok){alert('Export bloqueado por gating VIP1: '+vr.r);return;}}
var logs=[];for(var i=0;i<d.temLogs.length;i++)if(d.temLogs[i].flightId===f.id&&d.temLogs[i].legId===l.id)logs.push(d.temLogs[i]);
function sec(t,b){var h='<section><h3>'+esc(t+' - '+b.status)+'</h3>';if(b.type==='PAX'){var cp=cntPax(b,b.paxMode||'FULL');h+='<p><strong>Modo:</strong> '+esc(b.paxMode||'FULL')+' - '+cp.c+'/'+cp.t+'</p>';}else{h+='<ul>';for(var k=0;k<b.items.length;k++)h+='<li>'+(b.items[k].checked?'[x] ':'[ ] ')+esc(b.items[k].label)+(b.items[k].required?' (REQ)':'')+'</li>';h+='</ul>';}h+='<p><strong>Notas:</strong> '+esc(b.notes||'')+'</p><p><strong>ACK:</strong> '+esc((b.acks||[]).filter(function(a){return a.acknowledged;}).map(function(a){return a.role+' '+(a.name||'');}).join(' | ')||'--')+'</p></section>';return h;}
var r='<!doctype html><html><head><meta charset="utf-8" /><title>Safety Briefings Report</title><style>body{font-family:Arial,sans-serif;margin:20px;color:#000}h1,h2,h3{margin:0 0 8px}h2{margin-top:16px;border-top:1px solid #ddd;padding-top:10px}section{border:1px solid #ddd;border-radius:8px;padding:10px;margin:8px 0}table{width:100%;border-collapse:collapse;margin-top:8px}th,td{border:1px solid #ddd;padding:6px;font-size:12px;text-align:left;vertical-align:top}th{background:#f2f2f2}ul{margin-top:6px}</style></head><body>';
r+='<h1>Safety Briefings Report</h1><p><strong>Fecha:</strong> '+esc(f.dateISO)+'</p><p><strong>Aeronave:</strong> '+esc(f.aircraftType+' '+(f.tailNumber||''))+'</p><p><strong>Mision:</strong> '+esc(f.missionType||'NORMAL')+'</p><p><strong>Leg:</strong> '+esc((l.from||'--')+' -> '+(l.to||'--'))+'</p>';
r+='<h2>Briefings</h2>'+sec('Briefing Mision',m)+sec('Briefing Tripulacion',cB)+sec('Briefing Pasajeros',pB);
r+='<h2>TEM Logs</h2>';if(!logs.length)r+='<section><p>Sin logs.</p></section>';else{r+='<section><table><thead><tr><th>Hora</th><th>Fase</th><th>Sev</th><th>Threat</th><th>Error</th><th>UAS</th><th>Recovery</th><th>FACDEE</th></tr></thead><tbody>';for(i=0;i<logs.length;i++)r+='<tr><td>'+esc(logs[i].createdAt||'')+'</td><td>'+esc(logs[i].phase||'')+'</td><td>'+esc(logs[i].severity||'')+'</td><td>'+esc(logs[i].threat||'')+'</td><td>'+esc(logs[i].error||'')+'</td><td>'+esc(logs[i].uas||'')+'</td><td>'+esc(logs[i].recoveryAction||'')+'</td><td>'+esc(fac(logs[i].facdee))+'</td></tr>';r+='</tbody></table></section>';}
r+='<h2>Debrief</h2><section>';for(i=0;i<DEBRIEF.length;i++)r+='<p><strong>'+esc(DEBRIEF[i].l)+':</strong> '+esc(x.fields[DEBRIEF[i].id]||'')+'</p>';r+='<h3>Acciones correctivas</h3>';if(!x.actions.length)r+='<p>Sin acciones.</p>';else{r+='<ul>';for(i=0;i<x.actions.length;i++)r+='<li><strong>'+esc(x.actions[i].title||'--')+'</strong> - '+esc(x.actions[i].owner||'--')+' - '+esc(x.actions[i].dueDateISO||'--')+' - '+esc(x.actions[i].severity||'--')+' - '+esc(x.actions[i].status||'--')+'</li>';r+='</ul>';}r+='</section></body></html>';
var w=window.open('','_blank');if(!w){alert('No se pudo abrir la ventana de export.');return;}w.document.open();w.document.write(r);w.document.close();w.focus();w.print();}
function mutate(fn,re){var d=load(),f=getFlight(d,state.flightId)||defFlight(d),l=getLeg(f,state.legId);if(!l){l={id:uid(),from:'',to:'',etdISO:'',etaISO:''};f.legs.push(l);state.legId=l.id;}fn(d,f,l);f.updatedAt=now();save(d);if(re)render();}
function curB(d,f,l){if(state.route==='mission')return getB(d,f,l,'MISSION');if(state.route==='crew')return getB(d,f,l,'CREW');if(state.route==='pax')return getB(d,f,l,'PAX');if(state.route==='debrief')return getB(d,f,l,'DEBRIEF');return null;}
function rowTap(e){var rowEl=c(e.target,'.check-item');if(!rowEl)return false;if(rowEl.getAttribute('data-suppress-click')==='1'){e.preventDefault();e.stopPropagation();return true;}if(c(e.target,'input, textarea, select, button, a, [data-no-row-toggle]'))return false;var inp=q(rowEl,'.check-input');if(!inp)return false;e.preventDefault();inp.checked=!inp.checked;try{inp.dispatchEvent(new Event('change',{bubbles:true}));}catch(_e){var ev=document.createEvent('Event');ev.initEvent('change',true,true);inp.dispatchEvent(ev);}return true;}
function click(e){if(rowTap(e))return;var el=c(e.target,'[data-action]');if(!el){if(e.target===modal){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');}return;}var a=el.getAttribute('data-action');
if(a==='open-tem-modal'){modal.classList.add('show');modal.setAttribute('aria-hidden','false');return;}
if(a==='close-tem-modal'){modal.classList.remove('show');modal.setAttribute('aria-hidden','true');return;}
if(a==='save-tem-log'){temSave();return;}
if(a==='export-report'){exportR();return;}
if(a==='go'){setHash(el.getAttribute('data-route')||'hub',state.flightId,state.legId);return;}
if(a==='new-flight'){mutate(function(d){var f=mkFlight();d.flights.push(f);state.flightId=f.id;state.legId=f.legs[0].id;},false);setHash('hub',state.flightId,state.legId);return;}
if(a==='add-leg'){mutate(function(_d,f){var l={id:uid(),from:'',to:'',etdISO:'',etaISO:''};f.legs.push(l);state.legId=l.id;},true);return;}
if(a==='select-flight'){state.flightId=el.value;var d=load(),f=getFlight(d,state.flightId);if(f&&f.legs.length)state.legId=f.legs[0].id;setHash(state.route||'hub',state.flightId,state.legId);return;}
if(a==='select-leg'){state.legId=el.value;setHash(state.route||'hub',state.flightId,state.legId);return;}
if(a==='pax-mode'){state.paxMode=el.getAttribute('data-mode')==='QUICK'?'QUICK':'FULL';mutate(function(d,f,l){var b=getB(d,f,l,'PAX');b.paxMode=state.paxMode;},true);return;}
if(a==='show-emergency-card'){alert('Mostrar tarjeta de emergencia operacional del operador.');return;}
if(a==='save-briefing'){mutate(function(d,f,l){var b=curB(d,f,l);if(b&&b.status!=='DONE')b.status='IN_PROGRESS';},true);return;}
if(a==='done-briefing'){mutate(function(d,f,l){var b=curB(d,f,l);if(!b)return;if(b.type==='MISSION')applyVIP1(f,b);ensureAcks(b,f);var x=getD(d,f,l),r=canDone(f,b,x);if(!r.ok){alert('No se puede cerrar: '+r.r);return;}b.status='DONE';b.completedAt=now();},false);setHash('hub',state.flightId,state.legId);return;}
if(a==='save-debrief'){mutate(function(d,f,l){var b=getB(d,f,l,'DEBRIEF');if(b.status!=='DONE')b.status='IN_PROGRESS';},false);alert('Debrief guardado.');return;}
if(a==='done-debrief'){mutate(function(d,f,l){var b=getB(d,f,l,'DEBRIEF'),x=getD(d,f,l),r=canDone(f,b,x);if(!r.ok){alert('No se puede cerrar: '+r.r);return;}b.status='DONE';b.completedAt=now();},false);setHash('hub',state.flightId,state.legId);return;}
if(a==='action-add'){mutate(function(d,f,l){getD(d,f,l).actions.push({id:uid(),title:'',owner:'',dueDateISO:'',severity:'LOW',status:'OPEN'});},true);return;}
if(a==='action-del'){var idx=Number(el.getAttribute('data-idx'));mutate(function(d,f,l){var arr=getD(d,f,l).actions;if(idx>=0&&idx<arr.length)arr.splice(idx,1);},true);return;}
}
function change(e){var t=e.target;if(m(t,'.check-input')){var rowEl=c(t,'.check-item');if(!rowEl)return;var kind=rowEl.getAttribute('data-kind');mutate(function(d,f,l){var b=curB(d,f,l);if(!b)return;if(kind==='briefing-item'){var id=rowEl.getAttribute('data-item-id');for(var i=0;i<b.items.length;i++)if(b.items[i].id===id){b.items[i].checked=!!t.checked;b.status=b.status==='DONE'?'DONE':'IN_PROGRESS';}if(b.type==='MISSION')applyVIP1(f,b);}if(kind==='pax-item'){var k=rowEl.getAttribute('data-key');b.paxChecks[k]=!!t.checked;b.paxMode=state.paxMode;b.status=b.status==='DONE'?'DONE':'IN_PROGRESS';}if(kind==='ack-item'){var idx=Number(rowEl.getAttribute('data-ack-index'));if(idx>=0&&idx<b.acks.length){b.acks[idx].acknowledged=!!t.checked;b.acks[idx].acknowledgedAt=t.checked?new Date().toLocaleString():'';b.status=b.status==='DONE'?'DONE':'IN_PROGRESS';}}},true);return;}
if(m(t,'[data-flight-field]')){var ff=t.getAttribute('data-flight-field');mutate(function(_d,f){f[ff]=ff==='paxCount'?Number(t.value||0):t.value;},ff==='missionType');return;}
if(m(t,'[data-leg-field]')){var lf=t.getAttribute('data-leg-field');mutate(function(_d,_f,l){l[lf]=t.value;},false);return;}
if(m(t,'[data-crew-index]')){var ci=Number(t.getAttribute('data-crew-index'));mutate(function(_d,f){if(ci>=0&&ci<f.crew.length)f.crew[ci].name=t.value;},false);return;}
if(m(t,'[data-vip-item-id]')){var iid=t.getAttribute('data-vip-item-id'),vk=t.getAttribute('data-vip-key');mutate(function(d,f,l){var b=getB(d,f,l,'MISSION');applyVIP1(f,b);for(var i=0;i<b.items.length;i++)if(b.items[i].id===iid){b.items[i].details[vk]=t.value;b.status=b.status==='DONE'?'DONE':'IN_PROGRESS';}},false);return;}
if(m(t,'[data-ack-name-index]')){var ai=Number(t.getAttribute('data-ack-name-index'));mutate(function(d,f,l){var b=curB(d,f,l);if(b&&ai>=0&&ai<b.acks.length)b.acks[ai].name=t.value;},false);return;}
if(m(t,'[data-action-edit-idx]')){var xi=Number(t.getAttribute('data-action-edit-idx')),xk=t.getAttribute('data-action-edit-key');mutate(function(d,f,l){var arr=getD(d,f,l).actions;if(xi>=0&&xi<arr.length)arr[xi][xk]=t.value;},false);return;}
if(m(t,'[data-action="select-flight"]')||m(t,'[data-action="select-leg"]'))click({target:t,preventDefault:function(){},stopPropagation:function(){}});
}
function input(e){var t=e.target;if(m(t,'[data-briefing-notes]')){mutate(function(d,f,l){var b=curB(d,f,l);if(!b)return;b.notes=t.value;if(b.status!=='DONE')b.status='IN_PROGRESS';},false);return;}
if(m(t,'[data-debrief-field]')){var id=t.getAttribute('data-debrief-field');mutate(function(d,f,l){var x=getD(d,f,l);x.fields[id]=t.value;var b=getB(d,f,l,'DEBRIEF');if(b.status!=='DONE')b.status='IN_PROGRESS';},false);return;}
if(m(t,'[data-action-edit-idx]')||m(t,'[data-ack-name-index]')||m(t,'[data-vip-item-id]')||m(t,'[data-crew-index]')||m(t,'[data-leg-field]')||m(t,'[data-flight-field]'))change(e);
}
function key(e){if(e.key!==' '&&e.key!=='Enter')return;var rowEl=c(e.target,'.check-item');if(!rowEl)return;if(c(e.target,'input, textarea, select, button, a'))return;var inp=q(rowEl,'.check-input');if(!inp)return;e.preventDefault();inp.checked=!inp.checked;try{inp.dispatchEvent(new Event('change',{bubbles:true}));}catch(_e){var ev=document.createEvent('Event');ev.initEvent('change',true,true);inp.dispatchEvent(ev);}}
function tFind(id){for(var i=0;i<touch.length;i++)if(touch[i].id===id)return i;return -1;}
function tStart(e){for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i],rowEl=c(t.target,'.check-item');if(!rowEl)continue;touch.push({id:t.identifier,y:t.clientY,m:false,row:rowEl});}}
function tMove(e){for(var i=0;i<e.changedTouches.length;i++){var t=e.changedTouches[i],ix=tFind(t.identifier);if(ix<0)continue;if(Math.abs(t.clientY-touch[ix].y)>TOUCH_DY)touch[ix].m=true;}}
function tEnd(e){for(var i=0;i<e.changedTouches.length;i++){var ix=tFind(e.changedTouches[i].identifier);if(ix<0)continue;var r=touch[ix];if(r.m&&r.row){r.row.setAttribute('data-suppress-click','1');setTimeout(function(rr){return function(){if(rr.row)rr.row.removeAttribute('data-suppress-click');};}(r),450);}touch.splice(ix,1);}}
function fatal(msg){if(!app)return;app.innerHTML='<section class="card"><div class="card-head"><div><h2 class="card-title">Safety Briefings Error</h2></div></div><div class="card-body"><p>'+esc(msg)+'</p><p class="hint">Recarga la app. Si persiste, reporta este mensaje.</p></div></section>';}
window.addEventListener('error',function(e){fatal(e&&e.message?e.message:'Error inesperado en Safety module.');});
window.addEventListener('unhandledrejection',function(e){fatal(e&&e.reason?String(e.reason):'Promise rejection en Safety module.');});
function init(){modeInit();document.addEventListener('click',click);document.addEventListener('change',change);document.addEventListener('input',input);document.addEventListener('keydown',key);document.addEventListener('touchstart',tStart,{passive:true});document.addEventListener('touchmove',tMove,{passive:true});document.addEventListener('touchend',tEnd,{passive:true});document.addEventListener('touchcancel',tEnd,{passive:true});window.addEventListener('hashchange',render);window.addEventListener('beforeunload',function(){var d=load();save(d);});setInterval(function(){var d=load();save(d);},7000);var d=load(),f=defFlight(d),l=getLeg(f,'');if(!location.hash)setHash('hub',f.id,l?l.id:'');else render();}
init();
})();

